apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-app-deployment
  labels:
    app: js-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: js-app
  template:
    metadata:
      labels:
        app: js-app
    spec:
      containers:
      - name: js-app
        # This placeholder is replaced by your GitHub Action automatically
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 3000  # Ensure this matches your App's internal port
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: js-app-service
  annotations:
    # Ensure it creates a Public Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  # CHANGE: This triggers the Classic Load Balancer creation
  type: LoadBalancer
  selector:
    app: js-app
  ports:
    - protocol: TCP
      port: 80         # The port the world sees (HTTP)
      targetPort: 80 # The port your container listens on